### ISSUE TITLE
Local GeoJSON Data Does Not Display

### ISSUE THREAD

**Issue by flywire** [HandsOnDataViz/leaflet-map#40]
[README.md](https://github.com/HandsOnDataViz/leaflet-map/blob/master/README.md)
> This template illustrates simple and flexible methods for non-experts to create maps that require loading GeoJSON files and tileLayers from local directories and remote servers.

The online demo works well but when I downloaded the project the GeoJSON data does not display in chrome on Win10 despite it being in the `src` folder under the map.

**Comment by ilyankou** [comment]
Hi @flywire 

The reason is most likely a [cross-origin request (CORS) error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors). When you open `index.html` in your browser, it is served as a `file:` protocol and not `http:`, preventing you from loading local GeoJSON files.

To fix this, you can open your map using a local server (such as https://www.npmjs.com/package/live-server). If you install the package, navigate to the folder in the terminal, and then run `live-server` command, you will see the map appearing at an address `http://127.0.0.1:8080/` or similar, with GeoJSON files loading.

Alternatively put your GeoJSON files somewhere on the web (such as [GitHub Gist](https://gist.github.com/), or AWS S3 bucket), and in `script.js` change the URLs to fetch files from these remote locations using http/https instead of a local folder.

Another alternative is to stick with GitHub and modify the map there using the online interface or GitHub Desktop, and view the map in GitHub Pages (eg flywire.github.io/leaflet-map).

**Comment by flywire** [comment]
I agree with your response but that is not what the documentation describes. The issue should be explained clearly.

---

The following batch file will start a map of the same name under windows with chrome and disable-web-security option if the supporting files are in the same folder (ie double-click `map.bat` will start `map.html`):

`start chrome --disable-web-security --user-data-dir="C:/ChromeDevSession" "file:///%cd%/%~n0.html"`

**Comment by ilyankou** [comment]
Thanks @flywire, I added a section to this repo's [README](https://github.com/HandsOnDataViz/leaflet-map/blob/master/README.md).
